title: Arena Drible
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Pra quem ama futebol
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
permalink: /:slug/

# Build settings
theme: minima
plugins:
  - jekyll-feed
